### ISSUE TITLE
Есть проблема

### ISSUE THREAD

**Issue by kramber1024** [Lesion45/l1-wb#1]
Предлагаю переписать проект на более хороший язык, например, py или js

**Comment by LaryStef** [comment]
Я тоже заметил такую проблему, нужно решать быстрее, а то это **критично** для работоспособности приложения

**Comment by kramber1024** [comment]
> Я тоже заметил такую проблему, нужно решать быстрее, а то это **критично** для работоспособности приложения

Я создал эту проблему целых **ДВЕ НЕДЕЛИ НАЗАД**. Видимо автору репозитория не важен его же проект 😔

**Comment by Lesion45** [comment]
Привет! Спасибо огромное за твоё предложение! Я понимаю, что Python или JS могут показаться более привлекательными, но поверь, я выбрал этот язык не просто так. Он тоже умеет многое, хоть и выглядит иногда скромнее.

Прошу прощения за задержку с ответом. Две недели – это, конечно, немало, но знаешь, тут такое дело: я буквально разрывался между несколькими проектами, а ещё пытался успеть выпить хотя бы одну чашку чая в день 😅 Но твой issue точно не остался незамеченным, и я обязательно займусь им, как только смогу.

Так что не переживай, всё под контролем!
